### ISSUE TITLE
Observing error message 404 for device connection status change notification 

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/NotificationProxy#77]
Observing error message 404 when device connection status is changed, also observing notification success message in debug which indicating that notification is successfully delivered to subscriber.
```
[11:51:51.096] DEBUG (1): sending subscriber notification to: HTTP://x.x.x.x:xxxx/v1/regard-controller-attribute-value-change with content: {"notification-proxy-1-0:attribute-value-changed-notification":{"counter":1,"timestamp":"2024-03-04T11:51:51.086824462Z","resource":"/core-model-1-4:network-control-domain=live/control-construct=OpenDayLight1/logical-termination-point=513250004/layer-protocol=0/mount-point-1-0:mount-point-pac/mount-point-configuration","attribute-name":"connection-status","new-value":"connecting"}} - debugId: 'dacbe2e4-7d66-47bf-983b-285aa3d804a0'
[11:51:51.098] DEBUG (1): sending subscriber notification to: HTTP://x.x.x.x:xxxx/v1/notify-controller-attribute-value-changes with content: {"notification-proxy-1-0:attribute-value-changed-notification":{"counter":1,"timestamp":"2024-03-04T11:51:51.086824462Z","resource":"/core-model-1-4:network-control-domain=live/control-construct=OpenDayLight1/logical-termination-point=513250004/layer-protocol=0/mount-point-1-0:mount-point-pac/mount-point-configuration","attribute-name":"connection-status","new-value":"connecting"}} - debugId: 'f5ea60ba-ce87-4022-bf83-e362bff1f8ec'
[11:51:51.101] DEBUG (1): no subscribers for /v1/notify-controller-object-deletions, message discarded
[11:51:51.140] ERROR (1): error during subscriber-notification for /v1/notify-controller-attribute-value-changes - debugId: 'f5ea60ba-ce87-4022-bf83-e362bff1f8ec'
    err: {
      "message": "Request failed with status code 404",
      "name": "AxiosError",
      "stack":
          AxiosError: Request failed with status code 404
              at settle (/home/openbackhaul/NotificationProxy/node_modules/axios/dist/node/axios.cjs:1913:12)
              at IncomingMessage.handleStreamEnd (/home/openbackhaul/NotificationProxy/node_modules/axios/dist/node/axios.cjs:2995:11)
              at IncomingMessage.emit (node:events:525:35)
              at endReadableNT (node:internal/streams/readable:1358:12)
              at processTicksAndRejections (node:internal/process/task_queues:83:21)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
          "Blob": null
        },
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Content-Type": "application/json",
          "x-correlator": "65d5451f-C774-b9aD-cd81-A11fa77273A0",
          "trace-indicator": "1",
          "user": "NotificationProxy",
          "originator": "NotificationProxy",
          "customer-journey": "1",
          "operation-key": "Operation key not yet provided.",
          "User-Agent": "axios/1.5.1",
          "Content-Length": "384",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "method": "post",
        "url": "HTTP://x.x.x.x:xxxx/v1/notify-controller-attribute-value-changes",
        "data": "{\"notification-proxy-1-0:attribute-value-changed-notification\":{\"counter\":1,\"timestamp\":\"2024-03-04T11:51:51.086824462Z\",\"resource\":\"/core-model-1-4:network-control-domain=live/control-construct=OpenDayLight1/logical-termination-point=513250004/layer-protocol=0/mount-point-1-0:mount-point-pac/mount-point-configuration\",\"attribute-name\":\"connection-status\",\"new-value\":\"connecting\"}}"
      },
      "code": "ERR_BAD_REQUEST",
      "status": 404
    }
[11:51:51.211] DEBUG (1): subscriber-notification success, notificationType /v1/notify-controller-attribute-value-changes, target url: HTTP://x.x.x.x:xxxx/v1/regard-controller-attribute-value-change, result status: 204 - debugId: 'dacbe2e4-7d66-47bf-983b-285aa3d804a0'


```

**Comment by paulBMentopolis** [comment]
I am assuming both target endpoints where the notifications should be sent to are found on MWDI.

HTTP://x.x.x.x:xxxx/v1/regard-controller-attribute-value-change -> is valid, hence the message is successfully sent
HTTP://x.x.x.x:xxxx/v1/notify-controller-attribute-value-changes -> is not a valid endpoint on MWDI, so a "404 - not found" error is thrown

It seems the subscription was not configured correctly. If my assumption is wrong, please provide which application is the target for the forwarded notifications.

Please close the issue after checking my assumptions.
